# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=2.0.0
maven_group=net.ray
archives_name=better-tab
enabled_platforms=fabric
# Minecraft properties
minecraft_version=26.1
# Dependencies
fabric_loader_version=0.18.4
fabric_api_version=0.144.3+26.1